### ISSUE TITLE
Getting `Config file 'mkdocs.yml' does not exist` opening when TechDocs

### ISSUE THREAD

**Issue by dnicolacopoulos** [RoadieHQ/sample-service#95]
Hello,

I followed the basic Techdocs setup as described [here](https://roadie.io/blog/how-techdocs-works/#limitations-of-basic-techdocs) by adding `sample-service` to my Backstage `app-config.yaml` as follows:
```
catalog:
  locations:
    - type: url
      target: "https://github.com/RoadieHQ/sample-service/blob/main/catalog-info-docs-only.yaml"
```

By when I visit the TechDocs tab, I get the following error:
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/59613021/191512295-741be387-53a6-4eaa-bdd1-db69508492b9.png">

When I look in the `sample-service` root folder, I see that the mkdocs.yml file is [there](https://github.com/RoadieHQ/sample-service/blob/main/mkdocs.yml) so I'm not sure what the problem is.

Thanks,
